# Generated by Django 4.0.5 on 2022-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField(choices=[('one', 'Year 1'), ('two', 'Year 2'), ('three', 'Year 3'), ('four', 'Year 4')], default='one', max_length=50)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
